apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deliveryService.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: delivery-service
    app.kubernetes.io/part-of: cloudkitchen
spec:
  type: ClusterIP
  selector:
    app: delivery-service
  ports:
  - name: http
    port: {{ .Values.deliveryService.port }}
    targetPort: {{ .Values.deliveryService.port }}
