apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.menuService.hpa }}
  namespace: {{ .Values.namespace }}
  labels:
    app: menu-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.menuService.deploymentname }}
  minReplicas: {{ .Values.menuService.minReplicas }}
  maxReplicas: {{ .Values.menuService.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
