apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nats.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: nats
spec:
  clusterIP: None          # headless service governs the StatefulSet
  selector:
    app: nats
  ports:
  - name: client
    port: {{ .Values.nats.clientPort }}
    targetPort: {{ .Values.nats.clientPort }}
  - name: monitor
    port: {{ .Values.nats.monitorPort }}
    targetPort: {{ .Values.nats.monitorPort }}
