apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.paymentService.servicename }}
  namespace: {{ .Values.namespace }}
  labels:
    app: payment-service
    app.kubernetes.io/part-of: cloudkitchen
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - name: http
    port: {{ .Values.paymentService.port }}
    targetPort: {{ .Values.paymentService.port }}
