apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.dbUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
