apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: user-service
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_EXPIRY: {{ .Values.secrets.jwtExpiry | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  NATS_URL: "nats://{{ .Values.nats.servicename }}:{{ .Values.nats.clientPort }}"
